package net.witchkings.knightsofterrafirma.item.armor;

import com.magistuarmory.antiquelegacy.EpicKnightsAntiqueLegacy;
import com.magistuarmory.antiquelegacy.config.ArmorConfig;
import com.magistuarmory.item.armor.ArmorType;
import dev.architectury.platform.Platform;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.witchkings.knightsofterrafirma.KnightsOfTerraFirma;
import net.witchkings.knightsofterrafirma.config.ConfigArmor;


public final class AntiqueArmor {
    public static final ArmorConfig ARMOR_CONFIG = EpicKnightsAntiqueLegacy.CONFIG.armor;

    public static final ArmorType BLACK_BRONZE_ATTIC_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_attic_helmet"), new ResourceLocation("knightsofterrafirma:attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableAtticHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_BELL_CUIRASS = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_bell_cuirass"), new ResourceLocation("knightsofterrafirma:bell_cuirass"), 0.0f, 0.0f, new Integer[] { 0, 0, 210, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBellCuirass, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_BEOTIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_beotian_helmet"), new ResourceLocation("knightsofterrafirma:beotian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBeotianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZED_GALLEA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronzed_gallea"), new ResourceLocation("knightsofterrafirma:bronzed_gallea"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzedGallea, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_RIDGE_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_ridge_helmet"), new ResourceLocation("knightsofterrafirma:ridge_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeRidgeHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_COOLUS = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_coolus"), new ResourceLocation("knightsofterrafirma:coolus"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeCoolus, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_INTERCISA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_intercisa"), new ResourceLocation("knightsofterrafirma:intercisa"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeIntercisa, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_MELOS = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_melos"), new ResourceLocation("knightsofterrafirma:melos"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeMelos, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_MONTEFORTINO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_montefortino_helmet"), new ResourceLocation("knightsofterrafirma:montefortino_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeMontefortinoHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_MUSCLE_CUIRASS = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_muscle_cuirass"), new ResourceLocation("knightsofterrafirma:muscle_cuirass"), 0.0f, 0.0f, new Integer[] { 0, 0, 230, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeMuscleCuirass, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_NIEDERBIEBER_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_niederbieber_helmet"), new ResourceLocation("knightsofterrafirma:niederbieber_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeNiederbieberHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_PHRYGIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_phrygian_helmet"), new ResourceLocation("knightsofterrafirma:phrygian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzePhrygianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_PILOS_CLOSET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_pilos_closet"), new ResourceLocation("knightsofterrafirma:pilos"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzePilosCloset, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_PILOS = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_pilos"), new ResourceLocation("knightsofterrafirma:pilos"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzePilos, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SQUAMATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_squamata"), new ResourceLocation("knightsofterrafirma:squamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 190, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeSquamata, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_ROMAN_PARADE_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_roman_parade_helmet"), new ResourceLocation("knightsofterrafirma:roman_parade_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableRomanParadeHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_APULO_CORINTHIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_apulo_corinthian_helmet"), new ResourceLocation("knightsofterrafirma:apulo_corinthian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeApuloCorinthianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_CHALCIDIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_chalcidian_helmet"), new ResourceLocation("knightsofterrafirma:attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableChalcidianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_CORINTHIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_corinthian_helmet"), new ResourceLocation("knightsofterrafirma:corinthian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 175 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableCorinthianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_GREEK_GREAVES = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_greek_greaves"), new ResourceLocation("knightsofterrafirma:greek_greaves"), 0.0f, 0.0f, new Integer[] { 0, 200, 0, 0 }, new Integer[] { 0, 3, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableGreekGreaves, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_HAMATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_hamata"), new ResourceLocation("knightsofterrafirma:hamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 240, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.enableHamata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_HAMATA_OPTIO = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_hamata_optio"), new ResourceLocation("knightsofterrafirma:hamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 240, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.enableHamataOptio, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_HEDDERNHEIM_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_heddernheim_helmet"), new ResourceLocation("knightsofterrafirma:heddernheim_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableHeddernheimHelmet, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_ILLIRIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_illirian_helmet"), new ResourceLocation("knightsofterrafirma:illirian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableIllirianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_IRON_NIEDERBIEBER_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_iron_niederbieber_helmet"), new ResourceLocation("knightsofterrafirma:niederbieber_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableIronNiederbieberHelmet, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_MURMILLO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_murmillo_helmet"), new ResourceLocation("knightsofterrafirma:murmillo_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableMurmilloHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_MUSCULATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_musculata"), new ResourceLocation("knightsofterrafirma:musculata"), 0.0f, 0.0f, new Integer[] { 0, 0, 260, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableMusculata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_OFFICER_SQUAMATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_officer_squamata"), new ResourceLocation("knightsofterrafirma:officer_squamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 240, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableOfficerSquamata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_OPEN_ATTIC_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_open_attic_helmet"), new ResourceLocation("knightsofterrafirma:open_attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableOpenAtticHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_PROVOCATOR_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_provocator_helmet"), new ResourceLocation("knightsofterrafirma:provocator_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableProvocatorHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SECUTOR_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_secutor_helmet"), new ResourceLocation("knightsofterrafirma:secutor_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableSecutorHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SEGMENTATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_segmentata"), new ResourceLocation("knightsofterrafirma:segmentata"), 0.0f, 0.0f, new Integer[] { 0, 0, 245, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableSegmentata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_THRACIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_thracian_helmet"), new ResourceLocation("knightsofterrafirma:thracian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableThracianHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_CARDIOPHYLAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_cardiophylax"), new ResourceLocation("default"), 0.0f, 0.0f, new Integer[] { 0, 0, 190, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableCardiophylax, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_LEFT_GLADIATOR_SHOULDER_PAD = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_left_gladiator_shoulder_pad"), new ResourceLocation("knightsofterrafirma:left_gladiator_shoulder_pad"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 2, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableLeftGladiatorShoulderPad, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_RIGHT_GLADIATOR_SHOULDER_PAD = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_right_gladiator_shoulder_pad"), new ResourceLocation("knightsofterrafirma:right_gladiator_shoulder_pad"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 2, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableRightGladiatorShoulderPad, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_LEFT_HAND_MANIKA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_left_hand_manika"), new ResourceLocation("knightsofterrafirma:bronze_left_hand_manika"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 3, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeLeftHandManika, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_RIGHT_HAND_MANIKA = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_right_hand_manika"), new ResourceLocation("knightsofterrafirma:bronze_right_hand_manika"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 3, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeRightHandManika, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_MARS_OF_TODI_THORAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_mars_of_todi_thorax"), new ResourceLocation("knightsofterrafirma:thorax"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableMarsOfTodiThorax, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SCALE_THORAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_scale_thorax"), new ResourceLocation("knightsofterrafirma:thorax"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableScaleThorax, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_KUBAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_kuban_helmet"), new ResourceLocation("knightsofterrafirma:kuban_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKubanHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SCYTHIAN_SCALE_THORAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_scythian_scale_thorax"), new ResourceLocation("knightsofterrafirma:thorax"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableScythianScaleThorax, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SCYTHIAN_ATTIC_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_scythian_attic_helmet"), new ResourceLocation("knightsofterrafirma:attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableScythianAtticHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SCYTHIAN_SCALE_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_scythian_scale_helmet"), new ResourceLocation("knightsofterrafirma:scythian_scale_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeScythianScaleHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_ROMAN_GREAVES = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_roman_greaves"), new ResourceLocation("knightsofterrafirma:greek_greaves"), 0.0f, 0.0f, new Integer[] { 0, 150, 0, 0 }, new Integer[] { 0, 2, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeRomanGreaves, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_CELTIC_MONTEFORTINO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_celtic_montefortino_helmet"), new ResourceLocation("knightsofterrafirma:montefortino_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableCelticMontefortinoHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_LA_GORGE_MEILLET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_la_gorge_meillet"), new ResourceLocation("knightsofterrafirma:la_gorge_meillet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableLaGorgeMeillet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");

    public static final ArmorType BLACK_BRONZE_SAVA_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_sava_helmet"), new ResourceLocation("knightsofterrafirma:agen_port_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableSavaHelmet, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BLACK_BRONZE_WATERLOO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "black_bronze_waterloo_helmet"), new ResourceLocation("knightsofterrafirma:waterloo_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableWaterlooHelmet, Platform.isForge() ? "forge:ingots/black_bronze" : "c:black_bronze_ingots");


    public static final ArmorType BISMUTH_BRONZE_ATTIC_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_attic_helmet"), new ResourceLocation("knightsofterrafirma:attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableAtticHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_BELL_CUIRASS = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_bell_cuirass"), new ResourceLocation("knightsofterrafirma:bell_cuirass"), 0.0f, 0.0f, new Integer[] { 0, 0, 210, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBellCuirass, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_BEOTIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_beotian_helmet"), new ResourceLocation("knightsofterrafirma:beotian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBeotianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZED_GALLEA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronzed_gallea"), new ResourceLocation("knightsofterrafirma:bronzed_gallea"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzedGallea, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_RIDGE_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_ridge_helmet"), new ResourceLocation("knightsofterrafirma:ridge_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeRidgeHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_COOLUS = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_coolus"), new ResourceLocation("knightsofterrafirma:coolus"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeCoolus, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_INTERCISA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_intercisa"), new ResourceLocation("knightsofterrafirma:intercisa"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeIntercisa, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_MELOS = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_melos"), new ResourceLocation("knightsofterrafirma:melos"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeMelos, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_MONTEFORTINO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_montefortino_helmet"), new ResourceLocation("knightsofterrafirma:montefortino_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeMontefortinoHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_MUSCLE_CUIRASS = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_muscle_cuirass"), new ResourceLocation("knightsofterrafirma:muscle_cuirass"), 0.0f, 0.0f, new Integer[] { 0, 0, 230, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeMuscleCuirass, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_NIEDERBIEBER_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_niederbieber_helmet"), new ResourceLocation("knightsofterrafirma:niederbieber_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeNiederbieberHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_PHRYGIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_phrygian_helmet"), new ResourceLocation("knightsofterrafirma:phrygian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzePhrygianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_PILOS_CLOSET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_pilos_closet"), new ResourceLocation("knightsofterrafirma:pilos"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzePilosCloset, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_PILOS = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_pilos"), new ResourceLocation("knightsofterrafirma:pilos"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzePilos, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SQUAMATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_squamata"), new ResourceLocation("knightsofterrafirma:squamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 190, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeSquamata, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_ROMAN_PARADE_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_roman_parade_helmet"), new ResourceLocation("knightsofterrafirma:roman_parade_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableRomanParadeHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_APULO_CORINTHIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_apulo_corinthian_helmet"), new ResourceLocation("knightsofterrafirma:apulo_corinthian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeApuloCorinthianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_CHALCIDIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_chalcidian_helmet"), new ResourceLocation("knightsofterrafirma:attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableChalcidianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_CORINTHIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_corinthian_helmet"), new ResourceLocation("knightsofterrafirma:corinthian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 175 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableCorinthianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_GREEK_GREAVES = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_greek_greaves"), new ResourceLocation("knightsofterrafirma:greek_greaves"), 0.0f, 0.0f, new Integer[] { 0, 200, 0, 0 }, new Integer[] { 0, 3, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableGreekGreaves, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_HAMATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_hamata"), new ResourceLocation("knightsofterrafirma:hamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 240, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.enableHamata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_HAMATA_OPTIO = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_hamata_optio"), new ResourceLocation("knightsofterrafirma:hamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 240, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, ARMOR_CONFIG.enableHamataOptio, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_HEDDERNHEIM_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_heddernheim_helmet"), new ResourceLocation("knightsofterrafirma:heddernheim_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableHeddernheimHelmet, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_ILLIRIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_illirian_helmet"), new ResourceLocation("knightsofterrafirma:illirian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableIllirianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_IRON_NIEDERBIEBER_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_iron_niederbieber_helmet"), new ResourceLocation("knightsofterrafirma:niederbieber_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableIronNiederbieberHelmet, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_MURMILLO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_murmillo_helmet"), new ResourceLocation("knightsofterrafirma:murmillo_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableMurmilloHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_MUSCULATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_musculata"), new ResourceLocation("knightsofterrafirma:musculata"), 0.0f, 0.0f, new Integer[] { 0, 0, 260, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableMusculata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_OFFICER_SQUAMATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_officer_squamata"), new ResourceLocation("knightsofterrafirma:officer_squamata"), 0.0f, 0.0f, new Integer[] { 0, 0, 240, 0 }, new Integer[] { 0, 0, 5, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableOfficerSquamata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_OPEN_ATTIC_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_open_attic_helmet"), new ResourceLocation("knightsofterrafirma:open_attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableOpenAtticHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_PROVOCATOR_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_provocator_helmet"), new ResourceLocation("knightsofterrafirma:provocator_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableProvocatorHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SECUTOR_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_secutor_helmet"), new ResourceLocation("knightsofterrafirma:secutor_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableSecutorHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SEGMENTATA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_segmentata"), new ResourceLocation("knightsofterrafirma:segmentata"), 0.0f, 0.0f, new Integer[] { 0, 0, 245, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableSegmentata, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_THRACIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_thracian_helmet"), new ResourceLocation("knightsofterrafirma:thracian_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableThracianHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_CARDIOPHYLAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_cardiophylax"), new ResourceLocation("default"), 0.0f, 0.0f, new Integer[] { 0, 0, 190, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableCardiophylax, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_LEFT_GLADIATOR_SHOULDER_PAD = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_left_gladiator_shoulder_pad"), new ResourceLocation("knightsofterrafirma:left_gladiator_shoulder_pad"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 2, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableLeftGladiatorShoulderPad, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_RIGHT_GLADIATOR_SHOULDER_PAD = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_right_gladiator_shoulder_pad"), new ResourceLocation("knightsofterrafirma:right_gladiator_shoulder_pad"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 2, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableRightGladiatorShoulderPad, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_LEFT_HAND_MANIKA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_left_hand_manika"), new ResourceLocation("knightsofterrafirma:bronze_left_hand_manika"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 3, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeLeftHandManika, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_RIGHT_HAND_MANIKA = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_right_hand_manika"), new ResourceLocation("knightsofterrafirma:bronze_right_hand_manika"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 3, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeRightHandManika, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_MARS_OF_TODI_THORAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_mars_of_todi_thorax"), new ResourceLocation("knightsofterrafirma:thorax"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableMarsOfTodiThorax, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SCALE_THORAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_scale_thorax"), new ResourceLocation("knightsofterrafirma:thorax"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableScaleThorax, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_KUBAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_kuban_helmet"), new ResourceLocation("knightsofterrafirma:kuban_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKubanHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SCYTHIAN_SCALE_THORAX = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_scythian_scale_thorax"), new ResourceLocation("knightsofterrafirma:thorax"), 0.0f, 0.0f, new Integer[] { 0, 0, 200, 0 }, new Integer[] { 0, 0, 4, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableScythianScaleThorax, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SCYTHIAN_ATTIC_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_scythian_attic_helmet"), new ResourceLocation("knightsofterrafirma:attic_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 200 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableScythianAtticHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SCYTHIAN_SCALE_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_scythian_scale_helmet"), new ResourceLocation("knightsofterrafirma:scythian_scale_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeScythianScaleHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_ROMAN_GREAVES = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_roman_greaves"), new ResourceLocation("knightsofterrafirma:greek_greaves"), 0.0f, 0.0f, new Integer[] { 0, 150, 0, 0 }, new Integer[] { 0, 2, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableBronzeRomanGreaves, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_CELTIC_MONTEFORTINO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_celtic_montefortino_helmet"), new ResourceLocation("knightsofterrafirma:montefortino_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 160 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableCelticMontefortinoHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_LA_GORGE_MEILLET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_la_gorge_meillet"), new ResourceLocation("knightsofterrafirma:la_gorge_meillet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableLaGorgeMeillet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

    public static final ArmorType BISMUTH_BRONZE_SAVA_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_sava_helmet"), new ResourceLocation("knightsofterrafirma:agen_port_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 190 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableSavaHelmet, Platform.isForge() ? "forge:ingots/iron" : "c:iron_ingots");

    public static final ArmorType BISMUTH_BRONZE_WATERLOO_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bismuth_bronze_waterloo_helmet"), new ResourceLocation("knightsofterrafirma:waterloo_helmet"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 170 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableWaterlooHelmet, Platform.isForge() ? "forge:ingots/bismuth_bronze" : "c:bismuth_bronze_ingots");

}

