package net.witchkings.knightsofterrafirma.item.armor;

import com.magistuarmory.item.armor.ArmorType;
import com.magistuarmory.config.ArmorConfig;
import dev.architectury.platform.Platform;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.witchkings.knightsofterrafirma.config.ConfigArmor;

import static com.magistuarmory.item.armor.ArmorTypes.ARMOR_CONFIG;

public final class ModArmor {
    public static final ArmorType BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ConfigArmor.knightBlackSteel.enabled, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ConfigArmor.knightBlackSteel.enabled, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ConfigArmor.armetBlackSteel.enabled, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_BARBUTE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_barbute"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ConfigArmor.barbuteBlackSteel.enabled, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_HALFARMOR = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_halfarmor"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ConfigArmor.halfarmorBlackSteel.enabled, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_GOTHIC_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gothic_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_GOTHIC = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gothic"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_SALLET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_sallet"), new ResourceLocation("knightsofterrafirma", "sallet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_MAXIMILIAN_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_maximilian_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_MAXIMILIAN = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_maximilian"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_maximilian_helmet"), new ResourceLocation("knightsofterrafirma", "maximilian_helmet"), 1.25F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_JOUSTING_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_jousting_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_JOUSTING = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_jousting"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_JOUSTING_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_stechhelm"), new ResourceLocation("knightsofterrafirma", "stechhelm"), 1.25F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_KASTENBRUST_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_kastenbrust_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_KASTENBRUST = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_kastenbrust"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_GRAND_BASCINET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_grand_bascinet"), new ResourceLocation("knightsofterrafirma", "grand_bascinet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_PLATEMAIL_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platemail_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1F, 0.5F, new Integer[]{600, 700, 750, 500}, new Integer[]{2, 5, 6, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_PLATEMAIL = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platemail"), new ResourceLocation("default"), 1F, 0.5F, new Integer[]{600, 700, 750, 500}, new Integer[]{2, 5, 6, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_KETTLEHAT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_kettlehat"), new ResourceLocation("knightsofterrafirma", "kettlehat"), 1F, 0.5F, new Integer[]{600, 700, 750, 500}, new Integer[]{2, 5, 6, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType GOLD_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType GOLD_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gold_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType GOLD_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType SILVER_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_silver_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType SILVER_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_silver_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType SILVER_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_silver_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType ST_SILVER_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_sterling_silver_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType ST_SILVER_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_sterling_silver_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType ST_SILVER_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_sterling_silver_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType PLATINUM_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platinum_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType PLATINUM_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platinum_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType PLATINUM_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platinum_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BRASS_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_brass_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BRASS_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_brass_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BRASS_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_brass_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType ROSE_GOLD_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_rose_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType ROSE_GOLD_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_rose_gold_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType ROSE_GOLD_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_rose_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");


    public static final ArmorType SILVER_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "silver_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType SILVER_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "silver_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType STERLING_SILVER_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "sterling_silver_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType STERLING_SILVER_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "sterling_silver_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BRASS_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "brass_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BRASS_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "brass_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType PLATINUM_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "platinum_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType PLATINUM_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "platinum_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType ROSE_GOLD_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "rose_gold_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType ROSE_GOLD_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "rose_gold_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{460, 630, 670, 550}, new Integer[]{2,5,7,2}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");


    public static final ArmorType BLUESTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_GOLD_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_GOLD_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_gold_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_GOLD_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_SILVER_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_silver_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_SILVER_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_silver_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_SILVER_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_silver_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_ST_SILVER_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_sterling_silver_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_ST_SILVER_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_sterling_silver_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_ST_SILVER_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_sterling_silver_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_PLATINUM_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_platinum_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_PLATINUM_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_platinum_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_PLATINUM_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_platinum_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_BRASS_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_brass_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_BRASS_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_brass_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_BRASS_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_brass_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_ROSE_GOLD_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_rose_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_ROSE_GOLD_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_rose_gold_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_ROSE_GOLD_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_rose_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_GOTHIC_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_gothic_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_GOTHIC = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_gothic"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_SALLET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_sallet"), new ResourceLocation("knightsofterrafirma", "sallet"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_JOUSTING_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_jousting_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_JOUSTING = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_jousting"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_JOUSTING_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_stechhelm"), new ResourceLocation("knightsofterrafirma", "stechhelm"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_KASTENBRUST_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_kastenbrust_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_KASTENBRUST = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_kastenbrust"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_KASTENBRUST_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_grand_bascinet"), new ResourceLocation("knightsofterrafirma", "grand_bascinet"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_MAXIMILIAN_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_maximilian_chestplate"), new ResourceLocation("knightsofterrafirma", "blue_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_MAXIMILIAN = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_maximilian"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_maximilian_helmet"), new ResourceLocation("knightsofterrafirma", "maximilian_helmet"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");

    public static final ArmorType BLUESTEEL_BARBUTE = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_barbute"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");
    public static final ArmorType BLUESTEEL_HALFARMOR = new ArmorType(new ResourceLocation("knightsofterrafirma", "bluesteel_halfarmor"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/blue_steel" : "c:blue_steel_ingots");


    public static final ArmorType REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType GOLD_REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType GOLD_REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_gold_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType GOLD_REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType SILVER_REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_silver_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType SILVER_REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_silver_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType SILVER_REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_silver_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType ST_SILVER_REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_sterling_silver_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType ST_SILVER_REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_sterling_silver_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType ST_SILVER_REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_sterling_silver_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType PLATINUM_REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_platinum_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType PLATINUM_REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_platinum_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType PLATINUM_REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_platinum_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType BRASS_REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_brass_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType BRASS_REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_brass_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType BRASS_REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_brass_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType ROSE_GOLD_REDSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_rose_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType ROSE_GOLD_REDSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_rose_gold_knight"), new ResourceLocation("default"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType ROSE_GOLD_REDSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_rose_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 3F, 0.6F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType REDSTEEL_GOTHIC_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_gothic_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_GOTHIC = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_gothic"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_SALLET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_sallet"), new ResourceLocation("knightsofterrafirma", "sallet"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType REDSTEEL_JOUSTING_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_jousting_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_JOUSTING = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_jousting"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_JOUSTING_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_stechhelm"), new ResourceLocation("knightsofterrafirma", "stechhelm"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType REDSTEEL_KASTENBRUST_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_kastenbrust_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_KASTENBRUST = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_kastenbrust"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_KASTENBRUST_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_grand_bascinet"), new ResourceLocation("knightsofterrafirma", "grand_bascinet"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType REDSTEEL_MAXIMILIAN_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_maximilian_chestplate"), new ResourceLocation("knightsofterrafirma", "red_steel_armor"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_MAXIMILIAN = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_maximilian"), new ResourceLocation("default"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_maximilian_helmet"), new ResourceLocation("knightsofterrafirma", "maximilian_helmet"), 3F, 0.5F, new Integer[]{900, 100, 1050, 800}, new Integer[]{3, 6, 9, 4}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");

    public static final ArmorType REDSTEEL_BARBUTE = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_barbute"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");
    public static final ArmorType REDSTEEL_HALFARMOR = new ArmorType(new ResourceLocation("knightsofterrafirma", "redsteel_halfarmor"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{700, 800, 850, 600}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/red_steel" : "c:red_steel_ingots");


    public ModArmor() { }

}
