package net.witchkings.knightsofterrafirma.item.armor;

import com.magistuarmory.item.armor.ArmorType;
import net.witchkings.knightsofterrafirma.KnightsOfTerraFirma;
import com.magistuarmory.config.ArmorConfig;
import dev.architectury.platform.Platform;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.ArmorMaterials;
import net.minecraft.world.item.crafting.Ingredient;

import static com.magistuarmory.item.armor.ArmorTypes.ARMOR_CONFIG;

public final class ModArmor {
    public static final ArmorType BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_BARBUTE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_barbute"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_HALFARMOR = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_halfarmor"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_GOTHIC_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gothic_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_GOTHIC = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gothic"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_SALLET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_sallet"), new ResourceLocation("knightsofterrafirma", "sallet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_MAXIMILIAN_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_maximilian_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_MAXIMILIAN = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_maximilian"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_MAXIMILIAN_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_maximilian_helmet"), new ResourceLocation("knightsofterrafirma", "maximilian_helmet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_JOUSTING_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_jousting_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_JOUSTING = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_jousting"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_JOUSTING_HELMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_stechhelm"), new ResourceLocation("knightsofterrafirma", "stechhelm"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_KASTENBRUST_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_kastenbrust_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_KASTENBRUST = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_kastenbrust"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_GRAND_BASCINET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_grand_bascinet"), new ResourceLocation("knightsofterrafirma", "grand_bascinet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BLACKSTEEL_PLATEMAIL_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platemail_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_PLATEMAIL = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_platemail"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BLACKSTEEL_KETTLEHAT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_kettlehat"), new ResourceLocation("knightsofterrafirma", "kettlehat"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType GOLD_BLACKSTEEL_KNIGHT_CHESTPLATE = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gold_knight_chestplate"), new ResourceLocation("knightsofterrafirma", "black_steel_armor"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType GOLD_BLACKSTEEL_KNIGHT = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gold_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType GOLD_BLACKSTEEL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "blacksteel_gold_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType SILVER_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "silver_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType SILVER_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "silver_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType STERLING_SILVER_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "sterling_silver_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType STERLING_SILVER_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "sterling_silver_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType BRASS_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "brass_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType BRASS_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "brass_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType PLATINUM_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "platinum_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType PLATINUM_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "platinum_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public static final ArmorType ROSE_GOLD_STEEL_CEREMONIAL_ARMET = new ArmorType(new ResourceLocation("knightsofterrafirma", "rose_gold_steel_ceremonial_armet"), new ResourceLocation("knightsofterrafirma", "armet"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");
    public static final ArmorType ROSE_GOLD_STEEL_CEREMONIAL = new ArmorType(new ResourceLocation("knightsofterrafirma", "rose_gold_steel_ceremonial_knight"), new ResourceLocation("default"), 1.25F, 0.5F, new Integer[]{230, 315, 335, 275}, new Integer[]{2, 5, 8, 3}, 9, SoundEvents.ARMOR_EQUIP_IRON, ARMOR_CONFIG.enableKnightArmor, Platform.isForge() ? "forge:ingots/black_steel" : "c:black_steel_ingots");

    public ModArmor() { }

}
